// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdw_tL5Q-daczrNXFxlxw9ZUF32Ry7Fzc',
    appId: '1:670663163150:web:34215c938a5ce53cc46b5f',
    messagingSenderId: '670663163150',
    projectId: 'keepnote-f8db0',
    authDomain: 'keepnote-f8db0.firebaseapp.com',
    storageBucket: 'keepnote-f8db0.appspot.com',
    measurementId: 'G-JE9SC5HH7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRuTP5MDUAoWgzhoNIpx6EqAe1alAdc0',
    appId: '1:670663163150:android:81b605a019314aa8c46b5f',
    messagingSenderId: '670663163150',
    projectId: 'keepnote-f8db0',
    storageBucket: 'keepnote-f8db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPTsSvp2K3F4hclrJT1HW0-0Apk7Qk5t0',
    appId: '1:670663163150:ios:3a75dd4eed61fde2c46b5f',
    messagingSenderId: '670663163150',
    projectId: 'keepnote-f8db0',
    storageBucket: 'keepnote-f8db0.appspot.com',
    iosBundleId: 'com.example.keepNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPTsSvp2K3F4hclrJT1HW0-0Apk7Qk5t0',
    appId: '1:670663163150:ios:3a75dd4eed61fde2c46b5f',
    messagingSenderId: '670663163150',
    projectId: 'keepnote-f8db0',
    storageBucket: 'keepnote-f8db0.appspot.com',
    iosBundleId: 'com.example.keepNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdw_tL5Q-daczrNXFxlxw9ZUF32Ry7Fzc',
    appId: '1:670663163150:web:39254fbb1211b4b2c46b5f',
    messagingSenderId: '670663163150',
    projectId: 'keepnote-f8db0',
    authDomain: 'keepnote-f8db0.firebaseapp.com',
    storageBucket: 'keepnote-f8db0.appspot.com',
    measurementId: 'G-EDW0ZZ30G7',
  );
}
